
[package]
name = "mavlink"
version = "0.8.0"
authors = ["Todd Stellanova", "Michal Podhradsky", "Kevin Mehall", "Tim Ryan", "Patrick José Pereira", "Ibiyemi Abiodun"]
build = "build/main.rs"
description = "Implements the MAVLink data interchange format for UAVs."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/mavlink/rust-mavlink"
edition = "2018"

[build-dependencies]
crc16 = "0.3.3"
bytes = "0.4"
xml-rs = "0.2"
quote = "0.3"
lazy_static = "1.2.0"
serde = { version = "1.0.101", optional = true, features = ["derive"] }

[[bin]]
name = "mavlink-dump"
required-features = ["common"]

[dependencies]
crc16 = "0.3.3"
bytes = "0.4"
num-traits = "0.2"
num-derive = "0.2"
bitflags = "1.0.4"
serial = { version = "0.4", optional = true }
serde = { version = "1.0.101", optional = true }
byteorder = { version = "0.5", optional = true }

[features]
"ardupilotmega" = []
"asluav" = []
"autoquad" = []
"matrixpilot" = []
"minimal" = []
"paparazzi" = []
"python_array_test" = []
"slugs" = []
"standard" = []
"test" = []
"ualberta" = []
"uavionix" = []
"icarous" = []
"common" = []

"emit-description" = []
"emit-extensions" = []
"std" = ["byteorder"]
"udp" = []
"tcp" = []
"direct-serial" = []
default= ["std", "tcp", "udp", "direct-serial", "serial", "serde", "common"]

# build with all features on docs.rs so that users viewing documentation
# can see everything
[package.metadata.docs.rs]
all-features = true
